model:
  _yaml_: "../kfold.yaml"
  score_model:
    blocks_per_ckpt: 1
    ckpt_atom_stack: true
  diffusion_head:
    train_x_0_perturb_prob: 0.2
  confidence_head:
    blocks_per_ckpt: 1

train:
  _yaml_: "full.yaml"
  name: stage3
  seed: 3

  init_from_ema: ['trunk']

  loss:
    weights:
      bond: 1.0

  optimizer:
    max_lr: 0.0010
    lr_decay_factor: 1.0

  training:
    train_trunk: false
    train_diffusion_head: true
    train_confidence_head: true
    diffusion_batch_size: 24

    soar:
      enabled: true
      root_time_min: 0.2
      root_time_max: 0.8
      rollout_schedule_num_steps: 100
      rollout_step_size: 1.0
      auxiliary_samples_per_root: 2
      forward_retention_min: 0.5
      aux_loss_weight: 1.0

  data:
    max_chains: 20
    max_tokens: 768
    max_atoms: 9216
    max_sequence_tokens: 1536

    ccd_path: /data/ccd-train.pkl
    data_root: /data/
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        name: rcsb-train
        weight: 1.0

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        name: rcsb-val
